### ISSUE TITLE
Content is not resized, so scrollbar is visible

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#69] opened 2016-04-07 09:10 UTC
The Notice panel is not adapting it's size to the browser size (works in standalone mode)

![image](https://cloud.githubusercontent.com/assets/2656996/14346169/369ee05a-fcb1-11e5-8625-3ecdd4bf59d8.png)

**Comment by miyconst** [comment] 2016-04-07 10:40
@andwah the minimum width of the Layout is `1200px`, but the issue seems to be same as here: https://github.com/Starcounter/Warehouse/issues/68.

**Comment by miyconst** [comment] 2016-05-10 08:29
Closing this issue as duplicate of #68.

**Closed by miyconst** 2016-05-10 08:29 UTC
Labels: bug
